# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: k8s-servicedeployment
resources:
  k8s-servicedeployment:index:ServiceDeployment:
    isComponent: true
    inputProperties:
      allocateIPAddress:
        type: boolean
        description: Whether or not to allocate an IP address for the service.
      image:
        type: string
        description: Name of the image to deploy.
      isMiniKube:
        type: boolean
        description: Whether or not using minikube
      ports:
        type: array
        items:
          type: number
        description: Ports for service to listen on.
      replicas:
        type: number
        description: Number of replicas of the service to deploy.
    requiredInputs:
      - image
    properties:
      frontEndIp:
        type: string
        description: The front end IP
    required:
      - frontEndIp
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Kubernetes: 3.*
    namespaces:
      k8s-servicedeployment: K8sServiceDeployment
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/MitchellGerdisch/pulumi-k8s-servicedeployment/sdk/go/k8s-servicedeployment
  nodejs:
    dependencies:
      "@pulumi/kubernetes": "^3.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-kubernetes: ">=3.0.0,<4.0.0"
