# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ServiceDeploymentArgs', 'ServiceDeployment']

@pulumi.input_type
class ServiceDeploymentArgs:
    def __init__(__self__, *,
                 image: pulumi.Input[str],
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 is_mini_kube: Optional[pulumi.Input[bool]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[float]]]] = None,
                 replicas: Optional[pulumi.Input[float]] = None):
        """
        The set of arguments for constructing a ServiceDeployment resource.
        :param pulumi.Input[str] image: Name of the image to deploy.
        :param pulumi.Input[bool] allocate_ip_address: Whether or not to allocate an IP address for the service.
        :param pulumi.Input[bool] is_mini_kube: Whether or not using minikube
        :param pulumi.Input[Sequence[pulumi.Input[float]]] ports: Ports for service to listen on.
        :param pulumi.Input[float] replicas: Number of replicas of the service to deploy.
        """
        pulumi.set(__self__, "image", image)
        if allocate_ip_address is not None:
            pulumi.set(__self__, "allocate_ip_address", allocate_ip_address)
        if is_mini_kube is not None:
            pulumi.set(__self__, "is_mini_kube", is_mini_kube)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)

    @property
    @pulumi.getter
    def image(self) -> pulumi.Input[str]:
        """
        Name of the image to deploy.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: pulumi.Input[str]):
        pulumi.set(self, "image", value)

    @property
    @pulumi.getter(name="allocateIPAddress")
    def allocate_ip_address(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether or not to allocate an IP address for the service.
        """
        return pulumi.get(self, "allocate_ip_address")

    @allocate_ip_address.setter
    def allocate_ip_address(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allocate_ip_address", value)

    @property
    @pulumi.getter(name="isMiniKube")
    def is_mini_kube(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether or not using minikube
        """
        return pulumi.get(self, "is_mini_kube")

    @is_mini_kube.setter
    def is_mini_kube(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_mini_kube", value)

    @property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[float]]]]:
        """
        Ports for service to listen on.
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[float]]]]):
        pulumi.set(self, "ports", value)

    @property
    @pulumi.getter
    def replicas(self) -> Optional[pulumi.Input[float]]:
        """
        Number of replicas of the service to deploy.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "replicas", value)


class ServiceDeployment(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 image: Optional[pulumi.Input[str]] = None,
                 is_mini_kube: Optional[pulumi.Input[bool]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[float]]]] = None,
                 replicas: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        """
        Create a ServiceDeployment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] allocate_ip_address: Whether or not to allocate an IP address for the service.
        :param pulumi.Input[str] image: Name of the image to deploy.
        :param pulumi.Input[bool] is_mini_kube: Whether or not using minikube
        :param pulumi.Input[Sequence[pulumi.Input[float]]] ports: Ports for service to listen on.
        :param pulumi.Input[float] replicas: Number of replicas of the service to deploy.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceDeploymentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ServiceDeployment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ServiceDeploymentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceDeploymentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 image: Optional[pulumi.Input[str]] = None,
                 is_mini_kube: Optional[pulumi.Input[bool]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[float]]]] = None,
                 replicas: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceDeploymentArgs.__new__(ServiceDeploymentArgs)

            __props__.__dict__["allocate_ip_address"] = allocate_ip_address
            if image is None and not opts.urn:
                raise TypeError("Missing required property 'image'")
            __props__.__dict__["image"] = image
            __props__.__dict__["is_mini_kube"] = is_mini_kube
            __props__.__dict__["ports"] = ports
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["front_end_ip"] = None
        super(ServiceDeployment, __self__).__init__(
            'k8s-servicedeployment:index:ServiceDeployment',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter(name="frontEndIp")
    def front_end_ip(self) -> pulumi.Output[str]:
        """
        The front end IP
        """
        return pulumi.get(self, "front_end_ip")

